# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Jiyong' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jiyong
  
  pod 'RAMAnimatedTabBarController'
  pod 'SnapKit', '~> 0.15.0'

  target 'JiyongTests' do
    inherit! :search_paths
  end

  target 'JiyongUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
